### ISSUE TITLE
Multiple data export within the same project creates files with identical names

### ISSUE THREAD

**Issue by makostadima** [tercen/flowjo_export_operator#7]
Assume I have a project and two of the template workflows: the one with downsampling and the one without. If I run both on the same dataset, then the export function creates files with identical names wihtin the same directory. There's no way for th user to know which export data come from which run.

I'd argue that it is important that the export operator takes a parameter with which the user can define the name of the directory where the data are stored every time. 

Same behaviour will be observed, if I run the same template on the same data with different parameters on FlowSOM, for example.

**Comment by ginberg** [comment]
![export_operator_properties](https://user-images.githubusercontent.com/7089667/171566771-6cf5aa9d-82b1-4a07-b2ef-5496ce2164f1.png)

@makostadima there is already a property output_folder, does that fix the problem?

**Comment by makostadima** [comment]
Apologies I didn't check that before creating this issue.

Yes, that is what I am talking about. No idea why it didn't cross my mind checking the operator settings...
