### ISSUE TITLE
strange clustermapping

### ISSUE THREAD

**Issue by ginberg** [tercen/flowjo_export_operator#9]
after the [performance upgrade merge](https://github.com/tercen/flowjo_export_operator/pull/8), the clustermapping is looking strange and not what one would expect. Also, the NA value is missing
new:
![cluster_mapping_after_merge](https://user-images.githubusercontent.com/7089667/172326838-19d4e2ca-10ab-4a6e-814a-2ee1e7269331.png)

old:
![cluster_mapping_old](https://user-images.githubusercontent.com/7089667/172326772-f51ede9f-7fd1-4b83-bc5c-0ca6d47a7393.png)

**Comment by ginberg** [comment]
@agouy maybe you can have a look at it?

**Comment by agouy** [comment]
@ginberg thanks for catching this, having a look

**Comment by agouy** [comment]
@ginberg can you please test if version 1.1.1 solves your issue? If not, could you share with me a link to this workflow?

**Comment by ginberg** [comment]
thanks @agouy, it looks better now, but still a bit different. In the FlowSOM export there is no NA value. In the TrackSom export, there is a mapping from numeric to numeric where the cluster mapping is meant to be from character to numeric.

Here are the workflows that I have used for testing, there are 2 exporting maps to compare
https://stage.tercen.com/TestTeam/p/058949c1c8c27183fbfbf12f12f59327
https://stage.tercen.com/TestTeam/p/058949c1c8c27183fbfbf12f12f1f459

**Comment by agouy** [comment]
Hi @ginberg , I believe this is fixed in 0.1.2. I've tested it with TrackSOM in the project you've shared. Could you please have a look and confirm this is working when you have a chance?

The issue was coming from data.table::fwrite, which replaces NAs by empty strings by default, this behaviour is different from write.csv's one. Thanks for catching this

**Comment by ginberg** [comment]
hi @agouy, good to know about the behaviour of datatable::fwrite. I just looked at the clustermapping for FlowSom and it doesn't have the NA value, see https://stage.tercen.com/r/058949c1c8c27183fbfbf12f12ffccba
But I just had a call with Alex M, we want to change the input of this operator (so it's always numeric) so we don't need a clustermapping at all, so I think we should not spend time on this anymore..

**Comment by agouy** [comment]
Hi @ginberg , I've pushed a new version (0.2.0) based on Alex's suggestions.
It would be great if you could have a look and see if the generated output is as expected and works with the plugin (flowsom and tracksom have been updated as well and output the cluster numbers as integers). Feel free to let me know if anything needs to be updated

**Comment by ginberg** [comment]
closing since we are not using the clustermapping anymore
